version: '3'
services:

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - '4444:4444'
    networks:
      - my_network
    restart: always

  driver:
    container_name: driver_container
    build: .
    image: driver-image
    networks:
      - my_network
    restart: always
    volumes:
      - ./app_data:/data
networks:
  my_network: